services:
  # Dev machine. Backed by volumes to survive container re-deployments
  dev-mongo:
    stdin_open: true
    tty: true
    command: /bin/bash
    image: dev-mongo:latest
    privileged: true 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    volumes:
      - mongo:/root/mongo
      - sls:/root/sls
      - vscode-server:/root/.vscode-server
      - zsh-history:/root/.zsh_history
      - ~/.evergreen.yml:/root/.evergreen.yml
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro
      - ~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub:ro
      - ~/.ssh/known_hosts:/root/.ssh/known_hosts

volumes:
  mongo:
  sls:
  vscode-server:
  zsh-history: