#!/bin/bash
ABSOLUTE_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"
ws_playground_dir=$(dirname $(dirname "$ABSOLUTE_PATH"))/playgrounds

kill() {
	__enable_python_env
  echo "About to kill all processes" 
  __launch kill 
}

help(){
    echo
    echo -e "\033[1;4;32m""Functions:""\033[0;34m"
    compgen -A function
    echo
    echo -e "\033[1;4;32m""Aliases:""\033[0;34m"
    compgen -A alias
    echo
    echo -e "\033[0m"
}

list()
{
	__enable_python_env
	__launch list
}

clean() {
  kill
  echo "erasing data on $__dir"
  $__cmd_prefix rm -rf $__dir
}

launch()
{
	__enable_python_env
	__launch $@ 
}

init()
{
	__enable_python_env
	__init $@
}

initd()
{
	__enable_python_env
	__init --single $@
}

init-replica()
{
	__enable_python_env
	__init --replicaset --nodes 3 $@
}

#1 nodes x 2 shards + 1 node csrs
init-lite()
{
	__enable_python_env

	__init --replicaset --nodes 1 --sharded 2 $@

}

#3 nodes x 2 shards + 3 node csrs
init-cluster()
{
	__enable_python_env
	__init --replicaset --nodes 3 --sharded 2 --config 3 $@
}

init-from-url()
{
	__enable_python_env
	$_url=$__args[0]
	[[ -z $_url ]] && echo "Please run mcluster init-from-url <url>" && return 1;
	regex='(https?|ftp|file)://[-[:alnum:]\+&@#/%?=~_|!:,.;]*[-[:alnum:]\+&@#/%=~_|]'
	if [[ $_url =~ $regex ]]; then
		wget -O - $_url | tar xzvf - -C /tmp
		init-from-dbpath "/tmp/data/db/job0/resmoke/"
	else
		echo "Invalid url"
	fi
}

start()
{
	__enable_python_env
	__launch start --dir $__dir
}
connect()
{
	echo "connecting to $1"

	__enable_python_env
	local port=$1;
	[[ -z $1 ]] && port=27017;
	 $__cmd_prefix mongo --port $port && return 0;
}


#private ----------------------------------------

__launch()
{
	$__cmd_prefix mlaunch $@ --dir $__dir 
}

__init()
{
	echo "ready to init..."
	__launch init $@ 
}

__enable_python_env()
{
	echo "enabling python env"
	$__cmd_prefix . .venv/bin/activate
}

__set()
{
	#first argument it s one command , followings are arguments
	if [ -z "$__cmd" ]; then 
		__cmd=$1;
	else
		__args="$__args $1"
	fi
}

__add_to_path ()
{	
	#add to PATH if not already there
    if [[ "$PATH" =~ (^|:)"${1}"(:|$) ]]
    then
        return 0
    fi
    export PATH=${1}:$PATH
}

__parse_args()
{
	[[ -z ${__parsed_args} ]] && __parsed_args=true || return 0;

	__add_to_path ./build/debug/install/bin
	__add_to_path ./build/install/bin

	__cmd_prefix=;
	__dir="$HOME/.mcluster/cdata/"
	_playground_dir="$HOME/.mcluster/pg"
	__cmd=;
	__args=;

	while [[ $# -gt 0 ]]; do
		case $1 in
			--echo)
				__cmd_prefix=echo;
				shift
			;;
			*)
				__set $1;
				shift
			;;
		esac;
	done;
}

__parse_args $@
echo "ready to $__cmd"
$__cmd $__args
echo "Stay committed"
